### ISSUE TITLE
Cached video player not working ExoPlayer class not found please help

### ISSUE THREAD

**Issue by vaibhavmali123** [vikram25897/flutter_cached_video_player#41]
E/AndroidRuntime(  526): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayerFactory;
E/AndroidRuntime(  526): 	at com.lazyarts.vikram.cached_video_player.CachedVideoPlayerPlugin$VideoPlayer.<init>(CachedVideoPlayerPlugin.java:82)
E/AndroidRuntime(  526): 	at com.lazyarts.vikram.cached_video_player.CachedVideoPlayerPlugin.onMethodCall(CachedVideoPlayerPlugin.java:349)
E/AndroidRuntime(  526): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(  526): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(  526): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(  526): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(  526): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(  526): 	at android.os.Looper.loop(Looper.java:197)
E/AndroidRuntime(  526): 	at android.app.ActivityThread.main(ActivityThread.java:7807)
E/AndroidRuntime(  526): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  526): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(  526): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
E/AndroidRuntime(  526): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayerFactory" on path: DexPathList[[zip file "/data/app/com.arraypointer.india_learner-e1xlBXMLbGtvIS6vtN_Ilw==/base.apk"],nativeLibraryDirectories=[/data/app/com.arraypointer.india_learner-e1xlBXMLbGtvIS6vtN_Ilw==/lib/arm64, /data/app/com.arraypointer.india_learner-e1xlBXMLbGtvIS6vtN_Ilw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/AndroidRuntime(  526): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(  526): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(  526): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(  526): 	... 12 more

**Comment by kiloki-official** [comment]
Same problem. Useless packag.

**Comment by vikram25897** [comment]
@vaibhavmali123 Are you facing this issue in debug or release?

**Comment by kiloki-official** [comment]
Debug. thanks

**Comment by AbhishekDoshi26** [comment]
@kiloki-official Did you face this when your video is running for a longer time?

**Comment by anand1280** [comment]
Launching lib/main.dart on Redmi Note 9 Pro in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:59201/5tKqTsIg3N0=/ws
W/ackground_musi(17139): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(17139): Init c5447d [ExoPlayerLib/2.13.1] [curtana, Redmi Note 9 Pro, Xiaomi, 29]
D/AudioManager(17139): getStreamVolume isRestricted mode = 0
I/DpmTcmClient(17139): RegisterTcmMonitor from: $Proxy0
I/Process (17139): Sending signal. PID: 17139 SIG: 9
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
Lost connection to device.
Exited (sigterm)

**Comment by AbhishekDoshi26** [comment]
@anand1280 this is not related to cached_video_player. Please have a look at https://github.com/flutter/flutter/issues/73221 which might help you!
