### ISSUE TITLE
Failed to initialize decoder: OMX.qcom.video.decoder.avc

### ISSUE THREAD

**Issue by AbhayVAshokan** [vikram25897/flutter_cached_video_player#6]
None of the videos load in any screen. Restarting the app fixes the issue.
This issue is not permanent. It pops up every now and then after using the app for some time.

```
I/ExoPlayerImpl( 9860): Init c570691 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5 Pro, Xiaomi, 28]
I/OMXClient( 9860): IOmx service obtained
E/ACodec  ( 9860): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  ( 9860): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec( 9860): Codec reported err 0xfffffff4, actionCode 0, while in state 1
I/flutter ( 9860): UPDATED 5f13415a2bd6073e1d88b948 IN DATABASE
W/MediaCodec-JNI( 9860): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI( 9860): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer( 9860): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer( 9860): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer( 9860):    at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer( 9860):    at android.media.MediaCodec.<init>(MediaCodec.java:1811)
W/MediaCodecRenderer( 9860):    at android.media.MediaCodec.createByCodecName(MediaCodec.java:1792)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer( 9860):    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer( 9860):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/MediaCodecRenderer( 9860):    at android.os.Looper.loop(Looper.java:201)
W/MediaCodecRenderer( 9860):    at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal( 9860): Playback error.
E/ExoPlayerImplInternal( 9860): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [480, 854, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal( 9860):         at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 9860):         at android.os.Looper.loop(Looper.java:201)
E/ExoPlayerImplInternal( 9860):         at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal( 9860): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [480, 854, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal( 9860):         ... 9 more
E/ExoPlayerImplInternal( 9860): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal( 9860):         at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal( 9860):         at android.media.MediaCodec.<init>(MediaCodec.java:1811)
E/ExoPlayerImplInternal( 9860):         at android.media.MediaCodec.createByCodecName(MediaCodec.java:1792)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal( 9860):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal( 9860):         ... 10 more
```

**Comment by adamdupuis** [comment]
I'm finding this issue happens with any video player package that uses ExoPlayer after many videos have been initialized, for example an Instagram-like feed of videos that automatically play as you scroll them into view. I found [native_video_view](https://github.com/LJaraCastillo/native_video_view) that doesn't use ExoPlayer, but the player has it's own issues too.

**Comment by AbhayVAshokan** [comment]
I posted this issue because it appeared after I changed ```video_player``` to ```cached_video_player``` and I thought some part of additional code might be intefering with the ```exo_player```.

**Comment by ArjanAswal** [comment]
Any idea how to solve this issue? Facing the same error myself.
@adamdupuis Indeed initializing multiple videos causes this problem, disposing of the player doesn't work either.
Do you know of any alternative video player which also allows caching?

**Comment by rithikjain** [comment]
@ArjanAswal for me disposing the video controllers solved the issue. Maybe check if the videos are getting disposed properly. This player doesn't support error handling. So for now personally I am using the officail video_player by flutter and handling the cache on flutter by using flutter_cache_manager. For longer term, I might end up writing a native exoplayer caching lib with error handling.

**Comment by vikram25897** [comment]
@ArjanAswal @rithikjain These issues are mostly related to underlying libraries and not this plugin itself. That being said, I am working on a rewrite of this plugin, that'll help me keep this plugin synced with official `video_player` plugin.

**Comment by rithikjain** [comment]
@vikram25897 That will be amazing. As a lot of people have a real need for this as the video_player uses a lot of bandwidth because of streaming. Thanks.

**Comment by ArjanAswal** [comment]
@rithikjain Disposing the controller is not solving the problem for me. I am using the video player as an item in PageView.builder(). So their are multiple controllers and disposing and instantiating each of them is not solving the issue. The only problem with handling the cache using flutter_cache_manager is that the video gets downloaded 2 times.

[This](https://stackoverflow.com/a/61883216) solved my issue.

@vikram25897 [ I agree](https://github.com/google/ExoPlayer/issues/1286#issuecomment-200854838). Looking forward to the plugin. Also, this [fork](https://github.com/sanekyy/plugins/tree/caching) is what I am using right now as it is not showing the stated error. I am curious why and recommend checking it out.
