### ISSUE TITLE
build realse verison not work in latest verison ^2.0.4

### ISSUE THREAD

**Issue by heshesh2010** [vikram25897/flutter_cached_video_player#68]
* What went wrong:
Execution failed for task ':cached_video_player:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/hesham/StudioProjects/siyaq-mobile/build/cached_video_player/intermediates/merged_res/release/values/values.xml:141: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 40s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:408:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:574:7)

**Comment by Coder-Manuel** [comment]
Am also getting the same issue....

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cached_video_player:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/emmanuelbonke/dev/mobile/instadriver_partner/build/cached_video_player/intermediates/merged_res/release/values/values.xml:141: AAPT: error: resource android:attr/lStar not found.
```


Version:
`Flutter: 3.7.1`
`cached_video_player: ^2.0.4`

**Comment by joseespanaeduk** [comment]
Some news, i have the same error? This only occurs on Android, recently i build a IPA for firebase and everthing is ok

**Comment by aykutonen** [comment]
@joseespanaeduk Workaround

https://github.com/vikram25897/flutter_cached_video_player/issues/64#issuecomment-1514809365

**Comment by dicky7** [comment]
@aykutonen thank you it's worked
